### ISSUE TITLE
Failed fetching aliases for plugin nodejs

### ISSUE THREAD

**Issue by rplankenhorn** [jdxcode/rtx-action#56]
This action has been working fine all morning and then all of the sudden it started doing this every time on OS X.  Linux works fine:

```
Run jdxcode/rtx-action@v1
  
/usr/bin/curl https://rtx.pub/rtx-latest-macos-x64 --output /Users/anka/.local/share/rtx/bin/rtx
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 77 13.2M   77 10.2M    0     0  21.9M      0 --:--:-- --:--:-- --:--:-- 22.2M
100 13.2M  100 13.2M    0     0  27.8M      0 --:--:-- --:--:-- --:--:-- 28.1M
/bin/chmod +x /Users/anka/.local/share/rtx/bin/rtx
/Users/anka/.local/share/rtx/bin/rtx --version
1.27.9 macos-x64 (a5246dc 2023-03-27)
/Users/anka/.local/share/rtx/bin/rtx install
[DEBUG] $ /Users/anka/.local/share/rtx/plugins/java/bin/list-legacy-filenames 
[DEBUG] $ /Users/anka/.local/share/rtx/plugins/python/bin/list-legacy-filenames 
[DEBUG] $ /Users/anka/.local/share/rtx/plugins/ruby/bin/list-legacy-filenames 
[DEBUG] $ /Users/anka/.local/share/rtx/plugins/nodejs/bin/list-legacy-filenames 
[DEBUG] Files: ~/actions-runner/_work/xxxxx/xxxxx/.tool-versions, ~/actions-runner/_work/xxxxx/xxxxx/Gemfile, ~/.tool-versions
Installed Plugins: java, nodejs, pnpm, python, ruby
[DEBUG] /Users/anka/.local/share/rtx/bin/rtx install
[DEBUG] $ /Users/anka/.local/share/rtx/plugins/nodejs/bin/list-aliases 
[WARN] failed to resolve tool version: Failed fetching aliases for plugin nodejs: ~/.local/share/rtx/plugins/nodejs/bin/list-aliases exited with non-zero status: no exit status
[DEBUG] nodejs@14.21.3, pnpm@7.8.0, ruby@3.0.3, python@3.10.3
[DEBUG] $ /Users/anka/.local/share/rtx/plugins/nodejs/bin/list-aliases 
Error: 
   0: Failed fetching aliases for plugin nodejs: ~/.local/share/rtx/plugins/nodejs/bin/list-aliases exited with non-zero status: no exit status

Location:
   src/plugins/mod.rs:3[19](https://github.com/xxxxx/xxxxx/actions/runs/4566996480/jobs/8060246449#step:9:20)

Version:
   1.27.9 macos-x64 (a5246dc 20[23](https://github.com/xxxxx/xxxxx/actions/runs/4566996480/jobs/8060246449#step:9:24)-03-[27](https://github.com/xxxxx/xxxxx/actions/runs/4566996480/jobs/8060246449#step:9:28))

Suggestion: Run with RTX_DEBUG=1 for more information.

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

/Users/anka/actions-runner/_work/_actions/jdxcode/rtx-action/v1/webpack:/typescript-action/node_modules/@actions/exec/lib/toolrunner.js:592
                error = new Error(`The process '${this.toolPath}' failed with exit code ${this.processExitCode}`);
^
Error: The process '/Users/anka/.local/share/rtx/bin/rtx' failed with exit code 1
    at ExecState._setResult (/Users/anka/actions-runner/_work/_actions/jdxcode/rtx-action/v1/webpack:/typescript-action/node_modules/@actions/exec/lib/toolrunner.js:592:1)
    at ExecState.CheckComplete (/Users/anka/actions-runner/_work/_actions/jdxcode/rtx-action/v1/webpack:/typescript-action/node_modules/@actions/exec/lib/toolrunner.js:575:1)
    at ChildProcess.<anonymous> (/Users/anka/actions-runner/_work/_actions/jdxcode/rtx-action/v1/webpack:/typescript-action/node_modules/@actions/exec/lib/toolrunner.js:469:1)
    at ChildProcess.emit (node:events:527:[28](https://github.com/xxxxx/xxxxx/actions/runs/4566996480/jobs/8060246449#step:9:29))
    at maybeClose (node:internal/child_process:1092:16)
    at Socket.<anonymous> (node:internal/child_process:[45](https://github.com/xxxxx/xxxxx/actions/runs/4566996480/jobs/8060246449#step:9:46)1:11)
    at Socket.emit (node:events:[52](https://github.com/xxxxx/xxxxx/actions/runs/4566996480/jobs/8060246449#step:9:53)7:28)
    at Pipe.<anonymous> (node:net:709:12)
```

Contents of `.tool-versions`
```
nodejs 14.21.3
pnpm 7.8.0
ruby 3.0.3
python 3.10.3
java zulu-11.54.25

```

**Comment by jdxcode** [comment]
what's the output of `rtx doctor`? I think your nodejs plugin is just out of date.

**Comment by jdxcode** [comment]
this doesn't make sense, the `list-aliases` file was removed from the nodejs plugin

**Comment by rplankenhorn** [comment]
@jdxcode Let me try to do some cleanup on the runner.  I am using a self-hosted Mac runner and things tend to hang around whether you cache them or not.

**Comment by jdxcode** [comment]
I just did a test run which runs the nodejs plugin and it worked fine: https://github.com/jdxcode/rtx-action/actions/runs/4567163908

I suspect you're caching the plugin or something

**Comment by jdxcode** [comment]
I still don't really understand why this happened even with an old version of the plugin. I suppose it probably doesn't matter though.
